### ISSUE TITLE
Doesn't build with HPC-GAP

### ISSUE THREAD

**Issue by markuspf** [gap-packages/json#1]
Trying to compile this for HPC-GAP does not work. First stumbling block is that `aobjects.h` uses `new` as an identifier, which C++ does not like. Renaming this I end up with

```
src/json.cc:266:39: error: 'typedef UInt** (* GVarFunc)()' redeclared as different kind of symbol
 typedef Obj (* GVarFunc)(/*arguments*/);
```

Is the correct fix to just rename the clashing names? In that case I can just submit a pull request.

**Comment by ChrisJefferson** [comment]
I'm finding trying to build any package with a modern configure (io, json) errors with "can't find <atomic_ops.h>". Can you build IO?

However yes, the typedef wants renaming. The same problem exists in all packages based on PackageMaker, so there will have to be a bunch of fixes :)

**Comment by ChrisJefferson** [comment]
Actually, I've changed my mind -- probably better to just change HPC-GAP (as this is a newly introduced and rarely used function), rather than fix all the packages :)

**Comment by ChrisJefferson** [comment]
Done (not fixed the 'new', or the atomic_ops.h)
