### ISSUE TITLE
kernel functions for json are not available

### ISSUE THREAD

**Issue by algorithmx** [gap-packages/json#18]
```
gap> SetInfoLevel(InfoPackageLoading,4);

gap> LoadPackage("json");

```
gives output

```
#I  json: entering LoadPackage 
#I  json: PackageAvailabilityInfo for version 2.0.1
#I  json: kernel functions for json are not available.
#I  json: PackageAvailabilityInfo: the AvailabilityTest function returned false
#I  json: PackageAvailabilityInfo: no installed version fits
#I  json: return from LoadPackage, package is not available

```

Please explain and fix.

Gap version:
```
 ┌───────┐   GAP 4.10.0 of 01-Nov-2018
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64
 Configuration:  gmp 6.1.2, readline
 Loading the library and packages ...
```

**Comment by algorithmx** [comment]
This error prevents me from loading GAP Jupyter kernel ... Please fix asap, thank you !

**Comment by ChrisJefferson** [comment]
you need to build the JSON package. How did you install GAP, and did you build some packages by hand?

The easist option is to go into the 'pkg' directory of GAP and type:

../bin/BuildPackages.sh

That will (hopefully) build json, along with every other GAP package. It will take a while and produce a lot of output!

**Comment by fingolfin** [comment]
@algorithmx did that resolve the issue for you? Please reply
