### ISSUE TITLE
Warning about `sprintf` usage

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/json#30]
Compiling with clang on macOS I get this warning compiling JSON:
```
src/json.cc:214:21: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
                    sprintf((char*)out,"\\u%04X",(unsigned)u);
                    ^
```
A simple fix would be to cheat and use `snprintf` with a fake buffer size of 6 (or 7?! off-by-one errors... *sigh*). Why not, given that this function already "cheats" by allocating a static GAP string with space for len*6 bytes...

(BTW you could also replace `JSON_AppendCStr` by `AppendCStr` since you now require GAP 4.12 anyway...)

**Comment by ChrisJefferson** [comment]
Both fixed
