### ISSUE TITLE
JsonStringToGap( "{ key : \"value\" }" ) not supported

### ISSUE THREAD

**Issue by mohamed-barakat** [gap-packages/json#7]
Would it be possible to support the following?
```
gap> JsonStringToGap( "{ key : \"value\" }" );
Error, syntax error at line 1 near: key : "value" } in
  return JSON_STRING_TO_GAP( str ); at pkg/json/gap/json.gi:118 called from
<function "JsonStringToGap">( <arguments> )
 called from read-eval loop at line 8 of *stdin*
```

Currently only the following works:
```
gap> JsonStringToGap( "{ \"key\" : \"value\" }" );
rec( key := "value" )
```

**Comment by ChrisJefferson** [comment]
I will have a look. Obviously that isn't valid JSON, but on the other hand it can't really be mistaken for valid JSON.

Then have to decide if we should have a "strict" and "relaxed" version.. hmm..

**Comment by mohamed-barakat** [comment]
Here is the reason: The json-input of an arangosh command looks exactly like this, see, e.g.,

https://docs.arangodb.com/3.2/Manual/Indexing/Hash.html

**Comment by ChrisJefferson** [comment]
Can you find a specification of what language arangosh is accepting? I don't mind expanding to accept it, but I can't find what it actually is?

**Comment by fingolfin** [comment]
That's simply JavaScript

**Comment by fingolfin** [comment]
@mohamed-barakat I am confused: why do you need to parse *input* for arangosh in the first place?

**Comment by mohamed-barakat** [comment]
I would like to be able to copy simple json-input (e.g., not including js-procedures) from the ArangoDB manual as a string and have an easy way to convert it into a GAP record for further manipulations. It's mere convenience and hence not urgent.

**Comment by ChrisJefferson** [comment]
In the interest of cleaning up, I plan on closing this, unless anyone really wants it

**Comment by mohamed-barakat** [comment]
It can be closed.

**Comment by fingolfin** [comment]
@mohamed-barakat I had a look at the ArangoDB docs (For 3.10) and saw no examples that matched your examples. They all used strings as keys. My guess would be that they changed ("fixed"?) this in the past 5 years?

**Comment by mohamed-barakat** [comment]
Probably yes. I wasn't able to recover the context. Thanks for investigating.
